ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "primaryColor" TEXT NOT NULL DEFAULT '#00A859';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT NOT NULL DEFAULT '#005C2E';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "fontFamily" TEXT NOT NULL DEFAULT 'Inter';
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "heroTitle" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "heroSubtitle" TEXT;
ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "footerText" TEXT;
